name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and build
        run: |
          npm ci
          npm run build
        env:
          VITE_DEPLOY_ENV: ${{ vars.VITE_DEPLOY_ENV }}
          VITE_SERVER_URL: ${{ vars.VITE_SERVER_URL }}
          VITE_KAKAO_KEY: ${{ vars.VITE_KAKAO_KEY }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_HOTJAR_SITE_ID: ${{ vars.VITE_HOTJAR_SITE_ID }}
          VITE_HOTJAR_VERSION: ${{ vars.VITE_HOTJAR_VERSION }}
          VITE_GTM_ID: ${{ vars.VITE_GTM_ID }}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3 and invalidate CloudFront
        run: |
          BUILD_HASH=$(git rev-parse --short HEAD)-$(date +%Y%m%d-%H%M%S)

          # NOTE: index.html은 no-cache를 두어 매번 서버에 확인 요청 보내게
          aws s3 sync dist/ "s3://${{ secrets.S3_BUCKET_NAME }}/frontend/${BUILD_HASH}/" --cache-control "public, max-age=31536000" --exclude "*.html"
          aws s3 sync dist/ "s3://${{ secrets.S3_BUCKET_NAME }}/frontend/${BUILD_HASH}/" --cache-control "no-cache" --include "*.html"
          aws s3 sync "s3://${{ secrets.S3_BUCKET_NAME }}/frontend/${BUILD_HASH}/" "s3://${{ secrets.S3_BUCKET_NAME }}/frontend/current/" --delete

          # NOTE: asterisk를 사용해도 경로 패턴 당 계산하므로 전체 invalidation 수행
          aws cloudfront create-invalidation --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" --paths "/*"
